elbv3 types
opentelekomcloud-infra/octavia-proxy pull request #38
Opened 2021-07-30 14:39 UTC by anton-sidelnikov

2021-08-03 13:37 UTC, outcatcher requested changes

2021-08-03 13:37 UTC, outcatcher commented on octavia_proxy/api/drivers/elbv3/driver.py
> +from octavia_proxy.api.v2.types import load_balancer
Those imports can be in a single line

2021-08-03 13:37 UTC, outcatcher commented on octavia_proxy/api/v3/types/l7policy.py
> +from octavia_proxy.api.v3.types import pool
This can be in a single import line

2021-08-03 13:37 UTC, outcatcher commented on octavia_proxy/api/v3/types/listener.py
> +from octavia_proxy.api.v3.types import pool
Can be a single line

2021-08-03 13:37 UTC, outcatcher commented on octavia_proxy/api/v3/types/load_balancer.py
> +#        'listeners': 'listeners'}
Useless code?

2021-08-03 13:37 UTC, outcatcher commented on octavia_proxy/api/v3/types/load_balancer.py
> +        #            result.vip_qos_policy_id = data_model.vip.qos_policy_id
Not used

2021-08-03 13:37 UTC, outcatcher commented on octavia_proxy/api/v3/types/pool.py
> +from octavia_proxy.api.v3.types import member
Can be a one line

2021-08-03 13:51 UTC, anton-sidelnikov commented on octavia_proxy/api/v3/types/load_balancer.py
> +#        'listeners': 'listeners'}
yes)

2021-08-04 08:30 UTC, outcatcher approved these changes

2021-08-04 09:05 UTC, merged