Elb v3 pool
opentelekomcloud-infra/octavia-proxy pull request #46
Opened 2021-08-16 11:02 UTC by anton-sidelnikov

2021-08-17 14:33 UTC, outcatcher requested changes

2021-08-17 14:33 UTC, outcatcher commented on octavia_proxy/api/drivers/elbv3/driver.py
> +
Shouldn't here function return just `self.listener_get` result?

2021-08-17 14:33 UTC, outcatcher commented on octavia_proxy/api/drivers/elbv3/driver.py
> +            query_filter.pop('id')
Same as the previous comment

2021-08-17 14:33 UTC, outcatcher commented on octavia_proxy/api/v2/controllers/pool.py
> +        return None
Is this a valid return?

2021-08-17 14:34 UTC, anton-sidelnikov commented on octavia_proxy/api/v2/controllers/pool.py
> +        return None
yep

2021-08-17 14:49 UTC, Polina-Gubina approved these changes

2021-08-17 18:08 UTC, outcatcher approved these changes

2021-08-18 07:08 UTC, Polina-Gubina approved these changes

2021-08-18 07:27 UTC, lego963 approved these changes

2021-08-18 09:15 UTC, merged