Pagination
opentelekomcloud-infra/octavia-proxy pull request #94
Opened 2021-11-03 09:50 UTC by irina-pereiaslavskaia

Add pagination logic to controllers and unit tests for it.

2021-12-06 13:27 UTC, Polina-Gubina approved these changes

2021-12-06 14:03 UTC, anton-sidelnikov requested changes

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/types/pool.py
> +        LOG.debug('DATA_MODEL {}'.format(data_model))
Remove logs

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/types/load_balancer.py
> +        else:
I thought that it will be better than None

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/types/load_balancer.py
> +#       result.admin_state_up = data_model.is_admin_state_up
Fix

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/controllers/availability_zones.py
> +        # query_filter.update(query_params)
I will try to do this in another PR.

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/controllers/flavors.py
> +        # query_filter.update(query_params)
I will try to do this in another PR.

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/controllers/health_monitor.py
> +        # query_filter.update(query_params)
I will try to do this in another PR.

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/controllers/l7policy.py
> +        # query_filter.update(query_params)
I will try to do this in another PR.

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/controllers/l7rule.py
> +        # query_filter.update(query_params)
I will try to do this in another PR.

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/controllers/listener.py
> +        # query_filter.update(query_params)
I will try to do this in another PR.

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/controllers/load_balancer.py
> +        # query_filter.update(query_params)
I will try to do this in another PR.

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/controllers/member.py
> +        # query_filter.update(query_params)
I will try to do this in another PR.

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/controllers/pool.py
> +        # query_filter.update(query_params)
I will try to do this in another PR.

2021-12-16 11:38 UTC, irina-pereiaslavskaia commented on octavia_proxy/api/v2/controllers/quotas.py
> +        # query_filter.update(query_params)
I will try to do this in another PR.

2021-12-16 11:41 UTC, anton-sidelnikov submitted a review, later dismissed

2021-12-16 11:41 UTC, anton-sidelnikov commented
let's merge

2021-12-16 12:36 UTC, lego963 approved these changes

2021-12-16 12:47 UTC, Polina-Gubina approved these changes

2021-12-16 13:02 UTC, merged